terraform_aks_acr_rg_name = "terraform_rg"
terraform_aks_acr_rg_location = "West Europe"
terraform_acr_name = "akscontainerRegistry3339"
terraform_acr_sku = "Premium"
terraform_aks_acr_name = "terraform-aks1"
terraform_aks_acr_dns_prefix = "terraformaks1"
terraform_aks_acr_node_size = "Standard_D2_v2"